parameters:
    sknife.listener.exceptions.mapping: []

services:
    sknife.twig.extension.datatable:
        class: Fudge\Sknife\Twig\Extension\Functions\DatatableExtension
        tags:
            - { name: twig.extension }

    sknife.twig.extension.string:
        class: Fudge\Sknife\Twig\Extension\Functions\StringExtension
        tags:
            - { name: twig.extension }

    sknife.datatable:
        class: Fudge\Sknife\Service\Datatable
        arguments: [@service_container]

    sknife.form.type.extension.bootstrap:
        class: Fudge\Sknife\Form\Extension\BootstrapExtension
        tags:
            - { name: form.type_extension, alias: 'form' }

    sknife.ajax.response.builder:
        class: Fudge\Sknife\Service\AjaxResponseBuilder
        arguments: [@session]

    sknife.listener.login.user.timezone:
        class: Fudge\Sknife\EventListener\SecurityListener
        arguments: [@security.context, @session]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin}

    sknife.translatable:
        class: Fudge\Sknife\Service\Translatable
        arguments: [@doctrine.orm.entity_manager, %locale%]

    sknife.variable_parameter:
        class: Fudge\Sknife\Service\VariableParameter
        arguments: [@service_container]

    sknife.form.type.bootstrap_switch:
        class: Fudge\Sknife\Form\Type\BootstrapSwitch
        tags:
            - { name: form.type, alias: 'sknife_bootstrap_switch'}

    sknife.form.type.date_range:
        class: Fudge\Sknife\Form\Type\DateRangeType
        tags:
            - { name: form.type, alias: 'sknife_date_range'}

    sknife.listener.exceptions:
        class: Fudge\Sknife\EventListener\ExceptionListener
        arguments: [%sknife.listener.exceptions.mapping%]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}

#    security.access.permission_voter:
#            class: Fudge\Sknife\Authorization\Voter\PermissionVoter
#            public: false
#            tags:
#                - { name: security.voter }
